name: Build container image for GHCR
on:
  push: {}
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        base:
          - {image: 'r-ver', amdtag: '4.2.2', armtag: '4.2.2', outname: 'r-ver'}
          - {image: 'rstudio', amdtag: '4.2.2', armtag: 'latest-daily', outname: 'bioconductor'}
    name: Build branch images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        if: matrix.base.platform == 'arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.base.outname }}
          tags: |
            type=raw,value={{branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push container image to GHCR
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_IMAGE=rocker/${{ matrix.base.image }}
            arm64_tag=${{ matrix.base.armtag }}
            amd64_tag=${{ matrix.base.amdtag }}
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
