name: Docker Vulnerability Scan 

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: master

env:

  IMAGE_NAME: ${{ github.repository }}
  DEVEL_TAG: devel
  RELEASE_TAG: latest

jobs:
  
  scan-devel:
  
    name: devel vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - uses: azure/container-scan@v0
      name: devel scan
      with:
        image-name: ${{ github.repository }}:${{ env.DEVEL_TAG }}

  scan-release:
  
    name: release vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - uses: azure/container-scan@v0
      name: release scan
      with:
        image-name: ${{ github.repository }}:${{ env.RELEASE_TAG }}
