name: Docker Vulnerability Scan 

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - devel
      - RELEASE_*

env:

  IMAGE_NAME: bioconductor/bioconductor_docker
jobs:
  
  scan-images:
  
    name: devel vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      id: branch
      run: echo "name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

    - uses: azure/container-scan@v0
      name: devel scan
      with:
        image-name: ${{ env.IMAGE_NAME }}:${{ steps.branch.outputs.name }}
