name: Update latest tag to latest release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  update_latest:
    runs-on: ubuntu-latest
    steps:
    - name: Set defaults for schedule
      id: defs
      run: |
        echo releasetag=$(curl https://hub.docker.com/v2/repositories/bioconductor/bioconductor/tags?page_size=1000 | jq '.results[].name' | tr -d '"' | grep -v "-" | sort -n | grep RELEASE | tail -n 1)  >> $GITHUB_OUTPUT

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Update latest tag
      run: |
        docker pull bioconductor/bioconductor:${{steps.defs.outputs.releasetag}}
        IMAGEDIFF=$(diff <(docker inspect bioconductor/bioconductor:latest) <(docker inspect bioconductor/bioconductor:${{steps.defs.outputs.releasetag}}))
        if [ -z "$IMAGEDIFF" ]; then
          echo '"latest" tag is already "${{steps.defs.outputs.releasetag}}"'
        else
          cat << "EOF" > /tmp/latest_tag_list
          bioconductor/bioconductor:latest
          bioconductor/bioconductor_docker:latest
          ghcr.io/bioconductor/bioconductor:latest
          ghcr.io/bioconductor/bioconductor_docker:latest
          EOF
          cat /tmp/latest_tag_list | xargs -i bash -c 'docker tag bioconductor/bioconductor:${{steps.defs.outputs.releasetag}} {} && docker push {}'
        fi
